version: "3"
services:
  db:
    image: mariadb:11.4
    command: mariadbd --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=+09:00
    volumes:
      - ./MariaDB/data:/var/lib/mysql
      - ./MariaDB/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./MariaDB/sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3333:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: PasswordPassword
      MYSQL_DATABASE: prototype
      MYSQL_USER: root
      MYSQL_PASSWORD: PasswordPassword
      TZ: Asia/Tokyo
